### ISSUE TITLE
Trouble installing p2t

### ISSUE THREAD

**Issue by robot-army** [pcbre/pcbre#4]
(pcbre) robotarmy@robotarmy-MS-7A71:~/xxxxxx/pcbre/pcbre$ ~/usr/pcbre/bin/pcbre-launcher 
PCBRE cannot start because the following python packages are missing: p2t

(pcbre) robotarmy@robotarmy-MS-7A71:~/xxxxxx/pcbre/pcbre$ pip install p2t
Requirement already satisfied: p2t in /home/robotarmy/.local/lib/python3.10/site-packages (1.0)

I have no idea what I'm doing!

**Comment by clisystems** [comment]
Installing cython and then installing from git appears to work

pip3 install cython
pip3 install git+https://github.com/davidcarne/poly2tri.python.git

**Comment by denizzzka** [comment]
@clisystems 
```
pip3 install cython
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

**Comment by denizzzka** [comment]
(Actuallty, Cython is installed)
```
$ pipx install git+https://github.com/davidcarne/poly2tri.python.git
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-i7uanmiv/setup.py", line 4, in <module>
          import Cython
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Cannot determine package name from spec 'git+https://github.com/davidcarne/poly2tri.python.git'. Check package spec for errors.
```

There seems to be some problem with this package. And it has been removed from Debian
